/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SomeObject } from '../models/SomeObject';
import { HttpFile } from '../http/http';

export class WithNullableType {
    'arrayDataOrNull': Array<SomeObject> | null;
    'stringDataOrNull': string | null;
    'oneOfOrNull': SomeObject | null;
    /**
    * AliasDescription
    */
    'oneOfPrimitiveAliasOrNull': number | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "arrayDataOrNull",
            "baseName": "arrayDataOrNull",
            "type": "Array<SomeObject>",
            "format": ""
        },
        {
            "name": "stringDataOrNull",
            "baseName": "stringDataOrNull",
            "type": "string",
            "format": ""
        },
        {
            "name": "oneOfOrNull",
            "baseName": "oneOfOrNull",
            "type": "SomeObject",
            "format": ""
        },
        {
            "name": "oneOfPrimitiveAliasOrNull",
            "baseName": "oneOfPrimitiveAliasOrNull",
            "type": "number",
            "format": "int32"
        }    ];

    static getAttributeTypeMap() {
        return WithNullableType.attributeTypeMap;
    }

    public constructor() {
    }
}
