/**
 * Basic polymorphism example with discriminator
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
*/
package org.openapitools.server.models

import jakarta.validation.constraints.*
import jakarta.validation.Valid
import com.fasterxml.jackson.annotation.JsonProperty
/**
 * A pet cat
 *
 * @param huntingSkill The measured skill for hunting
 * @param petType 
 */


data class Cat (

    /* The measured skill for hunting */

    @JsonProperty("huntingSkill")
    @field:Valid
    @field:NotNull
    val huntingSkill: Cat.HuntingSkill,


    @JsonProperty("petType")
    @field:Valid
    @field:NotNull
    val petType: kotlin.String

) : Pet {

    /**
     * The measured skill for hunting
     *
     * Values: clueless,lazy,adventurous,aggressive
     */
    enum class HuntingSkill(val value: kotlin.String) {
        @JsonProperty(value = "clueless") clueless("clueless"),
        @JsonProperty(value = "lazy") lazy("lazy"),
        @JsonProperty(value = "adventurous") adventurous("adventurous"),
        @JsonProperty(value = "aggressive") aggressive("aggressive");
    }
}

