/**
 * Basic polymorphism example with discriminator
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
*/
package org.openapitools.server.models

import jakarta.validation.constraints.*
import jakarta.validation.Valid
import com.fasterxml.jackson.annotation.JsonProperty
/**
 * A pet dog
 *
 * @param petType 
 * @param packSize the size of the pack the dog is from
 */


data class Dog (


    @JsonProperty("petType")
    @field:Valid
    @field:NotNull
    val petType: kotlin.String,

    /* the size of the pack the dog is from */

    @JsonProperty("packSize")
    @field:Valid
    @field:NotNull
 @field:Min(0)    val packSize: kotlin.Int

) : Pet

