generatorName: java
outputDir: samples/client/petstore/java/webclient-sealedInterface
library: webclient
inputSpec: modules/openapi-generator/src/test/resources/3_0/petstore-with-fake-endpoints-models-for-testing.yaml
templateDir: modules/openapi-generator/src/main/resources/Java
additionalProperties:
  artifactId: sealed-interface-webclient
  hideGenerationTimestamp: "true"
  useOneOfInterfaces: true
  useSealedOneOfInterfaces: true
