/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param id Query
 * @param outcomes 
 */


data class ApiQuery (

    /* Query */
    @SerializedName("id")
    val id: kotlin.Long? = null,

    @SerializedName("outcomes")
    val outcomes: kotlin.collections.List<ApiQuery.Outcomes>? = null

) {

    /**
     * 
     *
     * Values: SUCCESS,FAILURE,SKIPPED
     */
    enum class Outcomes(val value: kotlin.String) {
        @SerializedName(value = "SUCCESS") SUCCESS("SUCCESS"),
        @SerializedName(value = "FAILURE") FAILURE("FAILURE"),
        @SerializedName(value = "SKIPPED") SKIPPED("SKIPPED");

        /**
        * Override [toString()] to avoid using the enum variable name as the value, and instead use
        * the actual value defined in the API spec file.
        *
        * This solves a problem when the variable name and its value are different, and ensures that
        * the client sends the correct enum values to the server always.
        */
        override fun toString(): kotlin.String = value.toString()

    }

}

