/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models


import com.fasterxml.jackson.annotation.JsonEnumDefaultValue
import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param id Query
 * @param outcomes 
 */


data class Query (

    /* Query */
    @get:JsonProperty("id")
    val id: kotlin.Long? = null,

    @get:JsonProperty("outcomes")
    val outcomes: kotlin.collections.List<Query.Outcomes>? = null

) {

    /**
     * 
     *
     * Values: SUCCESS,FAILURE,SKIPPED,unknown_default_open_api
     */
    enum class Outcomes(val value: kotlin.String) {
        @JsonProperty(value = "SUCCESS") SUCCESS("SUCCESS"),
        @JsonProperty(value = "FAILURE") FAILURE("FAILURE"),
        @JsonProperty(value = "SKIPPED") SKIPPED("SKIPPED"),
        @JsonProperty(value = "unknown_default_open_api") @JsonEnumDefaultValue unknown_default_open_api("unknown_default_open_api");

        /**
        * Override [toString()] to avoid using the enum variable name as the value, and instead use
        * the actual value defined in the API spec file.
        *
        * This solves a problem when the variable name and its value are different, and ensures that
        * the client sends the correct enum values to the server always.
        */
        override fun toString(): kotlin.String = value.toString()

    }

}

